services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_USER:-password}
      - POSTGRES_DB=tests
    volumes:
      - postgres_volume:/var/lib/postgresql/data

    networks:
      - postgres_network

  web:
    build: .
    ports:
      - 8000:8000
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_volume:
